### PR TITLE
Add cred helper wrappers for ECR and ACR

### PR DESCRIPTION
**Pull request by imjasonh**
This currently depends on https://github.com/google/go-containerregistry/pull/1227, so there's a `replace` in `go.mod` which should be removed after that's merged, and this should depend on ggcr@main

This will enable folks who want to auth with GCR, ECR and ACR to do so without using invoking cred helper executables, by doing:

```go
import (
   "github.com/docker-credential-magic/docker-credential-magic/pkg/amazon"
   "github.com/docker-credential-magic/docker-credential-magic/pkg/azure"
   "github.com/google/go-containerregistry/pkg/authn"
   "github.com/google/go-containerregistry/pkg/v1/google"
   "github.com/google/go-containerregistry/pkg/v1/remote"
)

func main() {
  kc := authn.NewMultiKeychain(
    authn.DefaultKeychain,
    google.Keychain,
    amazon.Keychain,
    azure.Keychain,
  )
  img, err := remote.Get(ref, remote.WithAuthFromKeychain(kc))
}
```

This also enables users to change the preferred ordering (if it matters), and to remove ones they don't care to take a dependency on.

We could also add a `kubernetes.NewKeychain(client)` that looks up `imagePullSecrets` in a K8s cluster and uses those, which would effectively give us an a la carte version of `k8schain`, and let us deprecate it.

cc @jonjohnsonjr @jdolitsky @mattmoor

### CODE REVIEW

**Comment by imjasonh** [comment]
I _think_ this could also mean that the magic cred helper could reduce to:

```go
func main() {
  b, _ := ioutil.ReadAll(os.Stdin)
  auth, _ := NewMultiKeychain(/* see above */).Resolve(string(b)) // interface wrapper elided
  _ := json.NewEncoder(os.Stdout, auth)
}
```

**Review by jdolitsky — CHANGES_REQUESTED** [review]
nice! lgtm. can you fix build error w/ go mod vendor?

**Review by jdolitsky — APPROVED** [review]
This lgtm

Will let @jonjohnsonjr and/or @mattmoor view before merging

**Comment by imjasonh** [comment]
Sounds like we might be putting these in sub-Go-modules in ggcr proper: https://github.com/google/go-containerregistry/pull/1231

**Pull request closed without merging**
